### ISSUE TITLE
undefined input_simple

### ISSUE THREAD

**Issue by nicholaswild** [elandesign/formtastic_calendar#2]
This looks super helpful and a promising compliment to formtastic.

I'm running into an issue and I'm not sure if it has to do a missing dependency or if something else might be going on.

undefined method `input_simple' for #<Formtastic::SemanticFormBuilder:0x0000000ce47f58>
/vendor/plugins/formtastic_calendar/lib/formtastic_calendar.rb:12:in`calendar_input'

besides the plugin install I have added the Rails Date Kit Helper and the made sure it was referenced in the application controller.

I'll keep looking at this but I was just wondering if I was missing something that might not have been called out in the docs yet or if someone else has encountered this.

Thanks

**Comment by rubybox** [comment]
same problem too!

**Comment by wakatara** [comment]
Yep, I have the same problem as well. Was wondeirng if it was because I'm using the newest version of formtastic ? Can't quite puzzle it out though if anyone has solved it would love a hand... otherwise I'm going to have to revert off formtastic and to basic form builder with the calendar_select_helper gem... =<  Would much, _much_ rather use this if I can get it working.

**Comment by wakatara** [comment]
OK, I've done a little more looking at this and it seems that the input_simple method is no longer a method in newer versions of Formtastic.

So, 

# \- (Object) input_simple(type, method, options)   protected  A method that deals with most of inputs (:string, :password, :file, :textarea and :numeric).

is deprecated (along with a bunch of others) in favour of :

# \- (Object) input(method, options = {})   Returns a suitable form input for the given method, using the database column information and other factors (like the method name) to figure out what you probably want.

# \- (Object) inputs(*args, &block) (also: #input_field_set) Creates an input fieldset and ol tag wrapping for use around a set of inputs.

So, I'm just trying to correct the relevant line in the plugin code (search for input_simple in your project if you need to find it or know how to fix this with the changes needed.

**Comment by elandesign** [comment]
Sorry for the delay in getting this fixed guys - I haven't updated my gems lately and was still using Formtastic 0.9.1.

I've just commited a new version that fixes the problem.

Paul.

**Comment by wakatara** [comment]
Works fabulously ! Thanks so much for fixing this Paul. Folding it into the app I'm working on now.

Very impressive you handling this all under the influence of flu meds as well !... =]
